### ISSUE TITLE
New option for the Pseudoinverse method

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/cpp#6]
Hi Murilo!

The pseudoinverse method (MatrixXd  pseudoInverse( const MatrixXd& matrix)) is implemented in the current version. It is a very useful function. But there is no option to compute the pseudoinverse with damped factor. It is possible to add it?

Thanks!

Juancho.

**Comment by bvadorno** [comment]
Hi Juancho,

We'll see what is the best strategy to implement this functionality in a coherent manner. Since DQ Robotics is not a general purpose linear algebra library and the damped least-square inverse usually makes sense (at least in the context of robotics) only when performing motion control, we'll probably implement it inside a control law in the same way we do in Matlab. 

For the moment, I recommend you implement locally your own version of the damped least-square inverse.

Cheers,
Bruno

**Comment by juanjqo** [comment]
Ok, I'll do it! 

Thanks.

**Comment by bvadorno** [comment]
Great. I'll close this issue for now. If we reopen it in the future, I'll let you know.

Cheers,
Bruno
